### ISSUE TITLE
Sendy Dockerfile?

### ISSUE THREAD

**Issue by rymir** [okfn/infra#110]
hi guys, we at https://expend.io are going to integrate with https://sendy.co.
We got a license and we were thinking of deploying it as a docker service in our ECS cluster. We see you created a `Dockerfile` for sendy (https://github.com/okfn/infra/blob/153c83baca99bc7415b62786f6ed6fea8bb1cc80/ansible/roles/docker/tasks/main.yml#L47), would you mind sharing it somehow?

**Comment by igorescobar** [comment]
@rymir Hope it helps: http://www.igorescobar.com/blog/2016/07/20/deploying-sendy-using-aws-elasticbeanstalk-and-docker/

**Comment by danfowler** [comment]
Thanks!
